/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.AlumnoData;
import AccesoADatos.InscripcionData;
import AccesoADatos.MateriaData;
import Dominio.Alumno;
import Dominio.Inscripcion;
import Dominio.Materia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pablo
 */
public class Inscripciones extends javax.swing.JInternalFrame {
    private List<Alumno> Alumnos;
    private List<Materia> Materias;
    private AlumnoData alumnoData;
    private MateriaData materiaData;
    private InscripcionData inscripcionData;
    private DefaultTableModel modelo;
    

    /**
     * Creates new form Inscripcion
     */
    public Inscripciones() {
        initComponents();
        alumnoData=new AlumnoData();
        materiaData=new MateriaData();
        inscripcionData=new InscripcionData();
        Alumnos= alumnoData.listarAlumnos();
        modelo=new DefaultTableModel();
        listaAlumnos();
        cabecera();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlSeleccion = new javax.swing.JLabel();
        jcbAlumnos = new javax.swing.JComboBox<>();
        jlTituloMateria = new javax.swing.JLabel();
        jcbMateriaIns = new javax.swing.JCheckBox();
        jcbMateriaNoIns = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabla = new javax.swing.JTable();
        jbInscribir = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbAnular = new javax.swing.JButton();

        jlTitulo.setText("Inscripcion");

        jlSeleccion.setText("Seleccion de Alumno");

        jlTituloMateria.setText("Listado de Materias");

        jcbMateriaIns.setText("Materias Inscriptas");
        jcbMateriaIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMateriaInsActionPerformed(evt);
            }
        });

        jcbMateriaNoIns.setText("Materias NO Inscriptas");
        jcbMateriaNoIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMateriaNoInsActionPerformed(evt);
            }
        });

        jtTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTabla);

        jbInscribir.setText("Inscribir");
        jbInscribir.setEnabled(false);
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbAnular.setText("Anular Inscripcion");
        jbAnular.setEnabled(false);
        jbAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jlTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jlTituloMateria)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlSeleccion)
                        .addGap(33, 33, 33)
                        .addComponent(jcbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jcbMateriaIns)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbMateriaNoIns))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbInscribir)
                            .addGap(59, 59, 59)
                            .addComponent(jbAnular)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSalir))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSeleccion)
                    .addComponent(jcbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jlTituloMateria)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMateriaIns)
                    .addComponent(jcbMateriaNoIns))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInscribir)
                    .addComponent(jbSalir)
                    .addComponent(jbAnular))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        // TODO add your handling code here:
        int seleccion=jtTabla.getSelectedRow();
        if(seleccion!=-1){
            Alumno alumno=(Alumno)jcbAlumnos.getSelectedItem();
            
            int idMateria=(Integer)modelo.getValueAt(seleccion,0);
            String nombre=(String)modelo.getValueAt(seleccion,1);
            int anio=(Integer)modelo.getValueAt(seleccion,2);
            Materia materia= new Materia(idMateria,nombre,anio,true);
            
            Inscripcion inscripcion=new Inscripcion(0,alumno,materia);
            inscripcionData.guardarInscripcion(inscripcion);
            borrarFila();            
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione una Materia");
        }
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularActionPerformed
        // TODO add your handling code here:
        int seleccion=jtTabla.getSelectedRow();
        if(seleccion!=-1){
            Alumno alumno=(Alumno)jcbAlumnos.getSelectedItem();
            
            int idMateria=(Integer)modelo.getValueAt(seleccion,0);           
            inscripcionData.eliminarInscripcionMateriAlumno(alumno.getIdAlumno(), idMateria);
            borrarFila();            
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione una Materia");
        }        
    }//GEN-LAST:event_jbAnularActionPerformed

    private void jcbMateriaInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMateriaInsActionPerformed
        // TODO add your handling code here:
        borrarFila();
        jcbMateriaNoIns.setSelected(false);
        cargaInscriptos();
        jbAnular.setEnabled(true);
        jbInscribir.setEnabled(false);       
    }//GEN-LAST:event_jcbMateriaInsActionPerformed

    private void jcbMateriaNoInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMateriaNoInsActionPerformed
        // TODO add your handling code here:
        borrarFila();
        jcbMateriaIns.setSelected(false);
        cargaNOInscriptos();
        jbInscribir.setEnabled(true);
        jbAnular.setEnabled(false);
    }//GEN-LAST:event_jcbMateriaNoInsActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void listaAlumnos(){
        for(Alumno lista:Alumnos){
            jcbAlumnos.addItem(lista);
        }
    }
    
    private void cargaInscriptos(){
        Alumno seleccion=(Alumno)jcbAlumnos.getSelectedItem();
        Materias=inscripcionData.materiasInscriptas(seleccion.getIdAlumno());
        
         for(Materia lista:Materias){
            modelo.addRow(new Object[]{lista.getIdMateria(), lista.getNombre(), lista.getAnio()});
        }
    }
    
    private void cargaNOInscriptos(){
        Alumno seleccion=(Alumno)jcbAlumnos.getSelectedItem();
        Materias= inscripcionData.materiasNOInscriptas(seleccion.getIdAlumno());
        
        for(Materia lista:Materias){
            modelo.addRow(new Object[]{lista.getIdMateria(), lista.getNombre(), lista.getAnio()});
        }
    }
    
    private void cabecera(){
        ArrayList<Object> titulos=new ArrayList<>();
        titulos.add("ID");
        titulos.add("Nombre");
        titulos.add("Año");
        for(Object filas:titulos){
            modelo.addColumn(filas);
        }
        jtTabla.setModel(modelo);
    }
    
    private void borrarFila(){
        int indice= modelo.getRowCount()-1;
        for(int i = indice;i>=0;i--){
            modelo.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnular;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Alumno> jcbAlumnos;
    private javax.swing.JCheckBox jcbMateriaIns;
    private javax.swing.JCheckBox jcbMateriaNoIns;
    private javax.swing.JLabel jlSeleccion;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlTituloMateria;
    private javax.swing.JTable jtTabla;
    // End of variables declaration//GEN-END:variables
}
